include (ExternalProject)
cmake_policy(SET CMP0114 NEW)

set(LIBXML2_TARGET external.libxml2)
set(LIBXML2_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET})
set(LIBXML2_SRC_DIR ${LIBXML2_INSTALL_DIR}/src/${LIBXML2_TARGET})
set(LIBXML2_INCLUDE_DIRS ${LIBXML2_SRC_DIR}/include)
set(LIBXML2_AN_INCLUDE_DIRS ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/external.libxml2-build)
set(LIBXML2_STATIC_LIBRARY ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/external.libxml2-build/Release/libxml2s.lib)
include_directories(${LIBXML2_INCLUDE_DIRS} ${LIBXML2_AN_INCLUDE_DIRS})

set(LIBXML2_GIT_REPOSITORY https://gitlab.gnome.org/GNOME/libxml2.git)
if(NOT DEFINED LIBXML2_TAG)
  set(LIBXML2_TAG master)
endif()

ExternalProject_Add(${LIBXML2_TARGET}
  PREFIX ${LIBXML2_TARGET}
  GIT_REPOSITORY ${LIBXML2_GIT_REPOSITORY}
  GIT_TAG ${LIBXML2_TAG}
  SOURCE_DIR ${LIBXML2_SRC_DIR}
  CONFIGURE_COMMAND cmake -S ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET} -B ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET}-build -D LIBXML2_WITH_ICONV=OFF -D LIBXML2_WITH_LZMA=OFF -D LIBXML2_WITH_ZLIB=OFF -D LIBXML2_WITH_PYTHON=OFF -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=OFF
  BYPRODUCTS ${LIBXML2_STATIC_LIBRARY}
  BUILD_COMMAND cmake --build ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET}-build --config Release --target libxml2
  INSTALL_COMMAND ""
)

ExternalProject_Get_Property(${LIBXML2_TARGET} SOURCE_DIR)

add_library(libxml2 STATIC IMPORTED)
add_dependencies(libxml2 ${LIBXML2_TARGET})
set_target_properties(libxml2 PROPERTIES 
                      IMPORTED_LOCATION ${LIBXML2_STATIC_LIBRARY}
            )
