include (ExternalProject)
cmake_policy(SET CMP0114 NEW)

set(LIBXML2_TARGET external.libxml2)
set(LIBXML2_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET})
set(LIBXML2_SRC_DIR ${LIBXML2_INSTALL_DIR}/src/${LIBXML2_TARGET})
set(LIBXML2_INCLUDE_DIRS ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET}/include/libxml)
set(LIBXML2_STATIC_LIBRARY ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/src/external.libxml2-build/Release/libxml2.lib)
set(LIBXML2_RUNTIME_LIBRARY ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/src/external.libxml2-build/Release/libxml2.dll)
include_directories(${LIBXML2_INCLUDE_DIRS})

set(LIBXML2_GIT_REPOSITORY https://gitlab.gnome.org/GNOME/libxml2.git)
if(NOT DEFINED LIBXML2_TAG)
  set(LIBXML2_TAG master)
endif()

ExternalProject_Add(${LIBXML2_TARGET}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}
  GIT_REPOSITORY ${LIBXML2_GIT_REPOSITORY}
  GIT_TAG ${LIBXML2_TAG}
  SOURCE_DIR ${LIBXML2_SRC_DIR}
  CONFIGURE_COMMAND cmake -S ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET} -B ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET}-build -D CMAKE_INSTALL_PREFIX=usr/local -D LIBXML2_WITH_ICONV=OFF -D LIBXML2_WITH_LZMA=OFF -D LIBXML2_WITH_ZLIB=OFF -D LIBXML2_WITH_PYTHON=OFF -D CMAKE_BUILD_TYPE=Release
  BYPRODUCTS ${LIBXML2_STATIC_LIBRARY} ${LIBXML2_RUNTIME_LIBRARY}
  BUILD_COMMAND cmake --build ${CMAKE_CURRENT_BINARY_DIR}/${LIBXML2_TARGET}/src/${LIBXML2_TARGET}-build --config Release --target libxml2
  INSTALL_COMMAND ""
  # INSTALL_COMMAND cmake --install ${LIBXML2_INSTALL_DIR}/src/external.libxml2-build
)

ExternalProject_Get_Property(${LIBXML2_TARGET} SOURCE_DIR)

add_library(libxml2 SHARED IMPORTED)
set_target_properties(libxml2 PROPERTIES 
                      IMPORTED_IMPLIB ${LIBXML2_STATIC_LIBRARY}
                      IMPORTED_LOCATION ${LIBXML2_RUNTIME_LIBRARY}
            )
add_dependencies(libxml2 ${LIBXML2_TARGET})
